### PR TITLE
Update helpers.js

### PR DESCRIPTION
**Pull request by gmcnaught**
Changing a console.log to a logger.debug, though it can likely just be removed?

### CODE REVIEW

**Comment by ktyacke** [comment]
Hey Grant, 
Looks good to me, but I'd ask if you could make it an info output instead of debug for this particular instance.

Thanks!

**Comment by gmcnaught** [comment]
Done!

**Comment by ktyacke** [comment]
Thanks Grant! Though reviewing the additional comments, it does seem your original inclination to simply remove the output is our best bet. I'll tackle that one. Thanks again!

**Comment by robertdown** [comment]
This was never resolved, vote to reopen

**Comment by ktyacke** [comment]
@robertdown What is the ask here? The change @gmcnaught submitted was merged..

**Pull request closed without merging**
