### PR TITLE
Make auth() in api.js chainable

### LINKED ISSUE #18: Fix Chaining or Remove from readme
In the readme it gives an [example of chaining call ](https://github.com/akamai-open/AkamaiOPEN-edgegrid-node#chaining). However, it appears that functionality was removed for example [this commit](https://github.com/akamai-open/AkamaiOPEN-edgegrid-node/commit/1cf44e78da9044fcd15f04f27ee7b9f8599a41e3). 

I'd be more than happy to submit a PR either removing the documentation or going through and adding back in the return statements I just need to know which direction the maintainers would like to take.

I personally like chaining but that's me.

### PR DESCRIPTION
**Pull request by cpitt**
Fixes #18 by adding chaining back to "public" api methods.

### CODE REVIEW

**Comment by cpitt** [comment]
Not sure it even makes sense to have send() be chainable as you would have to auth() again before send()ing unless you wanted to send the same req

**Comment by cpitt** [comment]
@ktyacke My PR doesn't add trailing whitespace it removes it.

**Comment by ktyacke** [comment]
So it does! Apologies.

**Comment by cpitt** [comment]
No worries 😄

**Pull request merged**
