### PR TITLE
simplify header canonicalization

### PR DESCRIPTION
**Pull request by mdb**
Please let me know what you think of this effort to simplify the process by which headers are canonicalized.

Thanks!

### CODE REVIEW

**Comment by mdb** [comment]
As noted in my commit message:

Akamai API authentication documentation suggests:

- there is no need to specify specific headers to sign; all can/should be signed, which simplifies the code
- there is no need to order the canonicalized headers

See documentation for further clarification:
https://developer.akamai.com/introduction/Client_Auth.html

Please let me know if I'm mistaken.

**Comment by mdb** [comment]
@ktyacke @JonathanBennett Please let me know if you all have thoughts on this PR. Thanks!

**Comment by JonathanBennett** [comment]
Hi @mdb - started replying but never finished.

Would be good to have an Akamai opinion here so I'm tagging in @maglietti who might be able to help.

Originally the documentation stated they had to be ordered alphabetically as far as I remember, and the documentation contradicts itself in the example, where they've ordered the headers as they had to be done before. Assumed though this is tested and is working for calls? Haven't had a chance to try it myself yet.

**Comment by mdb** [comment]
I'll stay posted for word from @maglietti, though it's my belief this works as desired.

As for testing, I have done some basic acceptance testing, though it's fairly difficult to perform functional/acceptance tests against the full range of functionality without a suitable GTM domain against which I can perform destructive/modifying actions with no customer-impacting consequence.

As an aside, I would love to be able to utilize a throwaway Akamai GTM domain, etc. against which we can perform such acceptance tests. @ktyacke - curious to hear if Akamai can provide such a thing.

**Comment by ktyacke** [comment]
@mdb @JonathanBennett Reviewing this now. @maglietti is unfortunately no longer with Akamai, so I will do my best to answer your questions.

**Comment by JonathanBennett** [comment]
@mdb @ktyacke If Akamai has such an account for development purposes of libraries that would be awesome.. Kyle?

**Comment by ktyacke** [comment]
@mdb The changes look good to me. I like the simplification, and think it will make the code a bit easier to digest. One question: I noticed you changed method name "canonicalize_headers" to "canonicalizeHeaders". The majority of the methods in these scripts are named using an underscore syntax. Are you thinking you'd like to move towards using camelCase for the naming convention?

**Comment by ktyacke** [comment]
@JonathanBennett We don't offer such an account at this time, but I'll look into seeing if this might be a feasible option for future releases. In the mean-time, would you be able to create a "QA" property on your account to test against?

**Comment by mdb** [comment]
@ktyacke Regarding the `camelCasing`, yes, ideally I'd like to standardize on `camelCased` method/variable names, given that JavaScript itself uses camel casing rather than `snake_case`. That said, I recognize this is a stylistic preference and I'm open to others' opinions.

**Comment by ktyacke** [comment]
@mdb I'm actually in favor of `camelCasing` myself, I just noted that the majority of the code is written using `snake_case` and wasn't sure if doing such a vast refactor would raise concerns with you or @JonathanBennett If you guys are ok with it, I am as well!

**Pull request merged**
