### PR TITLE
Fix edgegrid send throw error inside an async method

### PR DESCRIPTION
**Pull request by erdarun**

### CODE REVIEW

**Comment by ktyacke** [comment]
This PR is not passing the build tests. Please review, and make sure all tests are passing prior to submitting. You will want to double check any tests that interact with the methods you updated.

**Comment by jlfabi** [comment]
@erdarun please see pull request #21, which has been closed. 
@ktyacke  Do you have a time table as to when you are going to update the npm package?

Thanks,

Jason

**Comment by ktyacke** [comment]
Closing as duplicate.

**Comment by ktyacke** [comment]
@erdarun published to NPM v2.0.8

**Pull request closed without merging**
